title: Henri Siirtola
description: a Junior Web/Software Developer and datanome graduate with experience in several languages. 
Current interests include React and Electron.
<br><br>
<a href="www.linkedin.com/in/hsiirtola">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
