title: Henri Siirtola
description: >
  a Junior Web/Software Developer and datanome graduate with experience in several programming languages. 
  Current interests include React and Electron.
  <br><br>
  Currently studying at CoreSeer Company on a remote FastTrack course.
  <br><br>
  <br>
  <a href="https://www.linkedin.com/in/hsiirtola">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
