title: Henri Siirtola
logo: "/images/img.png?raw=true"
description: >
  Junior Web/Software Developer and datanome graduate with experience in several programming languages. 
  Current interests include React and Electron.
  <br><br>
  Currently seeking job opportunities.
  <br><br>
  <br>
  <a href="https://www.linkedin.com/in/hsiirtola">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
